FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=jazzy
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    locales \
    software-properties-common \
    sudo \
    && locale-gen en_US en_US.UTF-8 \
    && add-apt-repository universe -y \
    && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
      -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo "$UBUNTU_CODENAME") main" \
      > /etc/apt/sources.list.d/ros2.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
      ros-jazzy-desktop \
      ros-dev-tools \
      python3-colcon-common-extensions \
      python3-rosdep \
      python3-vcstool \
      ros-jazzy-ros-gz \
      ros-jazzy-moveit \
      ros-jazzy-ros2-control \
      ros-jazzy-ros2-controllers \
      ros-jazzy-joint-state-publisher-gui \
      ros-jazzy-xacro \
      ros-jazzy-tf-transformations \
      mesa-utils \
      libgl1-mesa-dri \
      libglx-mesa0 \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update

RUN useradd -ms /bin/bash ros \
    && echo "ros ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/ros \
    && chmod 0440 /etc/sudoers.d/ros

USER ros
WORKDIR /home/ros/ws

RUN echo "source /opt/ros/jazzy/setup.bash" >> /home/ros/.bashrc

CMD ["/bin/bash"]
