FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    locales \
    software-properties-common \
    sudo \
    && locale-gen en_US en_US.UTF-8 \
    && add-apt-repository universe -y \
    && curl -L -o /tmp/ros2-apt-source.deb \
      http://repo.ros2.org/ubuntu/main/pool/main/r/ros-apt-source/ros2-apt-source_1.2.0~jammy_all.deb \
    && dpkg -i /tmp/ros2-apt-source.deb \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
      ros-humble-desktop \
      ros-dev-tools \
      python3-colcon-common-extensions \
      python3-rosdep \
      python3-vcstool \
      ros-humble-ros-gz \
      ros-humble-moveit \
      ros-humble-ros2-control \
      ros-humble-ros2-controllers \
      ros-humble-joint-state-publisher-gui \
      ros-humble-turtlesim \
      ros-humble-xacro \
      ros-humble-tf-transformations \
      mesa-utils \
      libgl1-mesa-dri \
      libglx-mesa0 \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update

RUN useradd -ms /bin/bash ros \
    && echo "ros ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/ros \
    && chmod 0440 /etc/sudoers.d/ros

USER ros
WORKDIR /home/ros/ws

RUN echo "source /opt/ros/humble/setup.bash" >> /home/ros/.bashrc

CMD ["/bin/bash"]
