services:
  ros2-foxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros2-foxy
    image: ros2-foxy-sim:dev
    container_name: ros2-foxy-sim
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PULSE_SERVER: ${PULSE_SERVER}
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - ../src:/home/ros/ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg:rw
    working_dir: /home/ros/ws
    stdin_open: true
    tty: true
