FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=foxy
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg2 \
    lsb-release \
    locales \
    software-properties-common \
    sudo \
    && locale-gen en_US en_US.UTF-8 \
    && add-apt-repository universe -y \
    && curl -fsSL -o /usr/share/keyrings/ros-archive-keyring.gpg \
      https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu focal main" \
      > /etc/apt/sources.list.d/ros2.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
      ros-foxy-desktop \
      python3-argcomplete \
      python3-colcon-common-extensions \
      python3-rosdep \
      python3-vcstool \
      ros-foxy-gazebo-ros-pkgs \
      ros-foxy-robot-state-publisher \
      ros-foxy-joint-state-publisher-gui \
      ros-foxy-ros2-control \
      ros-foxy-ros2-controllers \
      ros-foxy-turtlesim \
      ros-foxy-xacro \
      mesa-utils \
      libgl1-mesa-dri \
      libglx-mesa0 \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update --include-eol-distros

RUN useradd -ms /bin/bash ros \
    && echo "ros ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/ros \
    && chmod 0440 /etc/sudoers.d/ros

USER ros
WORKDIR /home/ros/ws

RUN echo "source /opt/ros/foxy/setup.bash" >> /home/ros/.bashrc

CMD ["/bin/bash"]
